version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3

jobs:

  build:
    environment:
      - TZ: "/usr/share/zoneinfo/Canada/Toronto"
      - CONTAINER_NAME: "mgoubran/hypermapper"
    docker:
      - image: docker:18.06.3-ce-git
    working_directory: /tmp/src/HyperMapp3r
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          no_output_timeout: 60m
          command: |
            # Build docker image
            hypermapper_VERSION=$(cat /tmp/src/HyperMapp3r/hypermapper/__init__.py | tr -dc '0-9' | sed 's/./&./g')
            echo "hypermapper version is ${hypermapper_VERSION}"
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                --no-cache \
                -t ${CONTAINER_NAME} \
                -f /tmp/src/HyperMapp3r/Dockerfile \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Run Tests
          no_output_timeout: 2h
          command: |

             echo "Running tests:"
             docker run --entrypoint bash -it mgoubran/hypermapper -c "hypermapper seg_wmh --help"
             docker run --entrypoint bash -it mgoubran/hypermapper -c "hypermapper seg_wmh -t1 /src/hypermapp3r/data/test_case/t1.nii.gz -fl /src/hypermapp3r/data/test_case/fl.nii.gz -m /src/hypermapp3r/data/test_case/mask.nii.gz -n 1"


      - store_test_results:
          path: /home/circleci/out/tests


workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: mgoubran/hypermapper
          tag: latest
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with hypermapper Version
                command: |
                   docker tag mgoubran/hypermapper:latest mgoubran/hypermapper:0.1.0
